#!/usr/bin/env ruby

class Dataset

  attr :name, :used, :availible, :refer, :mountpoint

  def self.all
    list = `zfs list -H`
    list.split("\n").map{|x| Dataset.new(x)}
  end

  def self.current_dataset
    list = all.select do |dataset|
      Dir.pwd.index dataset.mountpoint
    end
    list.sort{|x,y| x.mountpoint.length <=> y.mountpoint.length }.last
  end

  def initialize string
    @name, @used, @availible, @refer, @mountpoint = string.split "\t"
  end

  def number_of_snapshots
    `ls -1 #{@mountpoint}/.zfs/snapshot`.split("\n").length
  end

  def snap
    system "zfs snapshot #{name}@#{number_of_snapshots + 1}"
  end

end


case ARGV[0]
when 'snap'
  dataset = Dataset.current_dataset
  dataset.snap
when 'i'
  dataset = Dataset.current_dataset
  puts dataset.name
  puts dataset.number_of_snapshots

end
