#!/usr/bin/env ruby

class Dataset

  attr :name, :used, :availible, :refer, :mountpoint

  def self.all
    list = `zfs list -H`
    list.split("\n").map{|x| Dataset.new(x)}
  end

  def initialize string
    @name, @used, @availible, @refer, @mountpoint = string.split "\t"
  end

end


datasets = Dataset.all


case ARGV[0]
when 'snap'
when 'i'
  list = []
  list = datasets.select do |dataset|
    Dir.pwd.index dataset.mountpoint
  end

  dataset = list.sort{|x,y| x.mountpoint.length <=> y.mountpoint.length }.last
  puts dataset.name

end
